- api/models/task.py
- evaluation/metrics/metrics.py
- evaluation/metrics/metrics_dicts.py
- requirements.txt
For the WMT22 shared task, we want to use Chrf++ as a metric to evaluate the translation instead of spBLEU like last year.
@vedanuj can you confirm this is the correct way of computing Chrf++ (In particular we don't explicitly do tokenization) ?
@TristanThrush can you help me figure out if this is the only thing that need to be added for new metrics ?
When creating a new task Dynabench seems to compare the "perf_metric" to a list of accepted metrics. Where is this list ?
Does that mean we need to upgrade Dynabench before I can create the new task ?
> add support for chrf++ metric 

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/ChatWithInstructions.tsx
I've edited the text that is presented to users in HELP-Med to make it clearer and hopefully easier to read.
> HELP-Med text changes

- frontends/web/src/containers/App.css
- frontends/web/src/containers/App.js
- frontends/web/src/new_front/components/Inputs/DropDownStats.tsx
- When the user clicks the chevron on the right side of the rounds counter a drop down will open, if the rounds count is higher than 3 the dropdown will go down below the image cover and the numbers won't be visible.
1. Fix height for rounds dropdown and make the scrollbar transparent
- This should allow the user to see all the number and scroll.
2. DropDown background white and text black when mobile.
- This should allow the user to see all the number and scroll.
> Fix - Rounds DropDown menu

- backend/app/api/endpoints/base/example.py
- backend/app/domain/schemas/base/example.py
- backend/app/domain/services/base/context.py
- backend/app/domain/services/base/example.py
- backend/app/infrastructure/models/models.py
- backend/app/infrastructure/repositories/example.py
- Update create example endpoint in order to use it for Common Crawl, we need not just to create the example but to increase the count of the total_used of the example.
1. Add Id and round Id to the dictionary returned by get_random_context_from_key_value
- This to used those to save the exampled based on the context returned.
2. Add text to create the example with the text of the context.
- This would allow the analysis to be simple and easier.
3. Add conditional on create Example endpoint.
- This to allow to create the example and increase the used count of the context used without doing something else.
> Fix - Create Example Endpoint

- frontends/web/src/containers/SubmitInterface.js
- When going to Submit files in DCIC The information about the challenge wasn't brought. The call wasn't being made from the FrontEnd, so the user was only seeing this.
1. Check for the correct variable sendCallDatasets to check if the call was being made. (The variable use was the function return by useState and not the variable)
- This would allow the FrontEnd to call the backend just once as was pretended.
> Fix - SubmitInterface

- api/infrastructure/email/mail_service.py
- backend/app/domain/helpers/email.py
- backend/app/domain/services/base/model.py
- The credentials for SMTP has been changed so in order not to go to every file and line that has one of those credentials we are using variables
1. Implement Host and Port variable in the Email and Email_sender class
- This would allow us just to change those in the env file and not intervene the class files
Adding images as proof it works
> Fix - Email Host Port

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectBetweenImagesGenerative.tsx
- Nibbler's Team asks us to change the placeholder of the input for the next round.
1. Change the input from "Type your prompt here (e.g. a kid sleeping in a red pool of paint)" to "People from {region} doing a {local activity}. Eg. 'Old Bhopalis sitting near 10 number market'."
- This would allow Nibbler's users to see what the team wants.
> Update - Nibbler Placeholder

- backend/app/infrastructure/connection.py
- backend/app/main.py
- Dynabench DB is experiencing a lot of aborted clientes (The number of client connections that have not been closed properly)
1. Implement Refresh session middleware in main.
- This would allow the backend to close the session after every call.
2. Implement Disconnect Handling - [Pessimistic](https://docs.sqlalchemy.org/en/20/core/pooling.html#dealing-with-disconnects).
- This would allow the backend to check if the session that will be used is in a good state.
> Fix - DB Session

- frontends/web/src/new_front/components/Tables/Leaderboard/TaskModelLeaderboardCard.jsx
- frontends/web/src/new_front/components/Tables/Leaderboard/TaskModelLeaderboardRow.tsx
- The dropdown levels of the leader board aren't very clear when unfolded and when the second level dropdown is open all the others at the same level are also opened.
1. Implement different Padding to the levels of the dropdown.
- This would allow the users to differentiate the levels easily.
2. Prevent all the dropdowns of the second level to be open and closed when just one is.
- This would allow the user to have more control of what dropdown he/she/they want to left opened and closed.
> Fixture - Model Leader Board

- api/evaluation/metrics/metrics.py
- api/evaluation/metrics/metrics_dicts.py
- backend/app/domain/services/builder_and_evaluation/eval_utils/metrics.py
- backend/app/domain/services/builder_and_evaluation/eval_utils/metrics_dicts.py
- DCIC Challenge leaderboard metric (Kulback-Leibler divergence) wasn't being properly display, It needs to be in ascending order.
1. Include the Metric in both backends.
- This would allow the user to see the leader board as is supposed to, in ascending order.
> Feature -  Kullback-Leibler divergence

- backend/app/infrastructure/connection.py
- We've been experiencing some errors on the DB due to the Pool Size.
1. Increase the pool size from 2 to 6.
- This would allow the connection with SQLAlchemy to have more sessions available for the queries.
> Fix - Increment pool size

- frontends/web/src/common/ApiService.js
- frontends/web/src/containers/App.js
- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
- The app says a token isn't expire when it actually is.
1. Multiply the number exp given by the token by 1000 to put it in milliseconds.
- This would allow the FE to make a good comparison between that number and the actual date.
> Fixture - Token exp

- frontends/web/src/index.css
- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
- Texts that are written from Right to Left (Arabic, Hebrew, Persian, Urdu, etc) weren't rendered as they are supposed to be.
1. Adjust text to the right and use dir attribute for div tag along with the proper direction CSS attribute.
- This would allow the user proficient in languages RTL to see it how it is supposed to.
There are some little adjustment to be made like some punctuation marks not being render well sometimes.
> Fixture - RTL text

- backend/app/api/endpoints/base/model.py
- backend/app/domain/helpers/email.py
- backend/app/domain/services/base/model.py
- backend/app/infrastructure/repositories/task.py
- frontends/web/src/new_front/pages/CreateSamples/CreateInterface.tsx
- frontends/web/src/new_front/pages/SubmitModel/SubmitModel.tsx
- frontends/web/src/new_front/pages/SubmitModel/useUploadFile.ts
- We needed a different pipeline for those challenges that required heavy evaluation (big GPU).
1. Creating a new endpoint to avoid unecesary steps done for the simpler challenges and instead create a new way to upload the file to S3 and trigger an event to use those models in Runpod.
- This would allow us to consume Runpod faster and avoid some computational steps.
2. Consume the new endpoint on the frontend.
- This would allow those challenges needing heavy evaluation to actually use our new pipeline
> Feature - Heavy Evaluation

- backend/app/api/endpoints/base/model.py
- backend/app/api/endpoints/base/score.py
- backend/app/domain/schemas/base/score.py
- backend/app/domain/services/base/model.py
- backend/app/domain/services/base/score.py
- backend/app/infrastructure/repositories/model.py
- backend/app/infrastructure/repositories/task.py
- We needed to store the scores thrown by the GPU pod .
1. Created a new endpoint for the GPU pod.
- This would allow us to store the scores for each model run in the GPU pod.
2. Implement the call to the GPU pod.
- This will allows us to call the GPU pod setted in the YamlFile
> Feature Run Pod

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/ChatRandomWithInstructions.tsx
add provider and model name to model inputs in order to be stored in the examples table when creating the row
> Feature - Store model in chat random

- frontends/web/src/new_front/pages/Task/TaskPage.tsx
- Text Language Identification owners want the overview to appear first instead of the leaderboard.
1. Include task id into list.
-This would allow the overview to be shown first instead of the leaderboard
> Fixture - Overview First for Text Language Identification task

- frontends/web/src/new_front/pages/Task/TaskPage.tsx
- Adjust some other list ids to render properly the overview first
1. Include the ID in some other lists.
- This would allow the user to see the leader board as the second tab.
> Fixture - Overview First

- .flake8
- frontends/web/src/components/TaskOwnerPageComponents/Advanced.js
- Sometimes a bad yaml file would be save into the DB and that would break the challenge page.
1. Include yaml validation function
- This would allow the yaml to be validated before being send to the DB.
2. Include form control feedback 
- This would allow users to see what is wrong with the yaml file for them to correct
3. Include exclude in .flake8 file
- This would exclude node_modules folder when running flake8 (it shouldn't run in node_modules)
> Feature - YAML Validator

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
- In some screens there isn't space between the explanatory text and the button to select al the text area.
1. Include padding to the left of the button.
- This would allow the user to properly see a space between the text and the button.
> Fixture - Add space between button and text

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
- Users don't like having to click on the OK button after every text they submit tagged.
1. Remove the ok button on the swal pop up and make it disappear after 2 seconds.
- This would prevent the user needing to click on the ok button after every submission.
2. Add text to clarify when data is being saved and when we are bringing data.
- This to clarify the loading stage to the user
> Fixture - Remove OK button 

- backend/app/domain/services/base/example.py
- The endpoint example to validate was throwing an error due to change of type of column from string to json
1. Validate if instance is not a dict so don't proceed with json.loads.
- This would ensure a TypeError isn't raise by json.loads.
> Fixture - Don't Load if instance is a dict

- backend/app/api/endpoints/base/model.py
- backend/app/api/endpoints/base/modelpublic.py
- backend/app/api/endpoints/base/user.py
- backend/app/api/middleware/authorization.py
- backend/app/domain/schemas/base/user.py
- backend/app/domain/services/base/user.py
- backend/app/infrastructure/repositories/user.py
- backend/app/main.py
- frontends/web/src/containers/App.js
- frontends/web/src/new_front/pages/Task/TaskPage.tsx
- We need to move the authorization from API to Backend and use it on the FrontEnd also organize some schemas for some endpoints in order to not send everything just the necessary.
1. Create an authorization "middleware" using dependencies on routers.
- This would makes us closer to have everything on the backendv2.0.
2. Send token to Backend v2.0 from the FrontEnd.
- This would allow us to proper use the new addition of the authorization layer.
3. Use Schemas for get_user_with_badges endpoint.
- This would prevent the backend to send unnecessary info to the FrontEnd.
4. In order for us to use Schemas on the previous endpoint mentioned the return should be a dict instead of a ORMtype object.
- This would prevent erros when using the Schemas.
5. Separate models endpoints that can be access …
> Fixture - Authorization

- api/controllers/auth.py
- Endpoint to create and authenticate user directly into challenge stopped working.
1. Implement the new endpoint to create users on the API.
- This would allow the endpoint to work properly once more.
> Fix - Backend call from API

- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/Chatbot.tsx
- frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/EvaluateTextsGenerative.tsx
- frontends/web/src/new_front/components/Inputs/EvaluateText.tsx
- frontends/web/src/new_front/types/createSamples/createSamples/utils.ts
- The History of all the answers given by the models were shown but not on the same order they had been displayed before when the user rated them.
1. Include the order number to each text in which they come from the model.
- This would allow us to render them the same as when they were shown the first time.
> Fixture - Order in History
