mlcommons/dynabench

frontends/web/src/containers/FloresTaskPage.js, frontends/web/src/containers/ModelPage.js
Copied over from #37  made by @SyedAbi  to bypass the CLA taking too much time.
=> Front-End Landing Page - Adding African + Removing Grid

new_builder_evaluation/app/domain/evaluation.py
Changed the output of the evaluation method to include the named metric, for dynascore calculation.
=> Include metric for dynascore computation

frontends/web/src/new_front/pages/Landing/Features.tsx, frontends/web/src/new_front/pages/Landing/Header.tsx, frontends/web/src/new_front/pages/Landing/Landing.tsx, frontends/web/src/new_front/pages/Landing/TrustedBy.tsx
This PR introduces design improvements and responsive functionality to the landing page. The changes aim to enhance the visual appeal and user experience of the landing page while ensuring it adapts gracefully to different screen sizes.
- **Design Enhancements:** 
- Improved the overall visual design of the landing page.
- Updated hero section.
- **Responsive Design:**
- Introduced responsive design elements to ensure a seamless experience on various devices.
- Adjusted layout, spacing, and font sizes for different screen sizes (desktop, tablet, mobile).
- Implemented media queries with Tailwind to handle breakpoints effectively.
**Desktop version**
**Mobile version**
=> feat: Responsive design in landing 

backend/app/api/endpoints/base/model.py, backend/app/domain/schemas/base/model.py, backend/app/domain/services/base/model.py, backend/requirements.txt, frontends/web/src/new_front/components/Buttons/TaskActionButtons.tsx, frontends/web/src/new_front/components/Buttons/TaskActionButtons_new.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationButtonActions.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/Chatbot.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/EvaluateTextsGenerative.tsx, frontends/web/src/new_front/components/Inputs/EvaluateText.tsx, frontends/web/src/new_front/components/Modals/CreateProposalTask.tsx, frontends/web/src/new_front/components/Tables/Leaderboard/UserLeaderBoardCSV.tsx, frontends/web/src/new_front/pages/CreateSamples/ValidateSamples.tsx, frontends/web/src/new_front/pages/Landing/Header.tsx, frontends/web/src/new_front/pages/Login/LoginPage.tsx, frontends/web/src/new_front/pages/ProfilePage/ProfilePage.tsx, frontends/web/src/new_front/pages/Submissions/SubmitPrediction.tsx, frontends/web/src/new_front/pages/Task/LeaderBoard.jsx, frontends/web/src/new_front/utils/helpers/functions/LoginFunctions.js
This PR introduces several important enhancements and fixes to our platform. Here are the main highlights:
- Added the functionality to include the CSV leaderboard title as a property in the YAML file, specifically for Nibbler challenge.
- Made the necessary modifications in the Perdi create interface.
- Implemented the addition of metadata when creating a new example.
- Fixed a critical issue related to the login process that was causing some weird behavior.
=> feat: Minor fixes

backend/app/domain/services/utils/llm.py, backend/app/domain/services/utils/templates.py
This PR implements custom templates for conversational models. It also includes changeable parameters for OpenAI, Cohere and Anthropic models from the YAML file.
- The templates file contains both a heading and a footer where any instructions meant for the system should be included
-  Created yaml fields for all the available parameters for the conversational models implemented using OpenAI's, Cohere's and Anthropic's APIs.
=> Include templates

backend/app/api/endpoints/base/model.py, backend/app/domain/services/base/context.py, backend/app/domain/services/base/model.py, backend/app/domain/services/utils/llm.py, backend/app/domain/services/utils/multi_generator.py, backend/requirements.txt
This PR implements Replicate Handler for the factory of LLM Providers, and reimplemented all handlers to work asynchronously
-  This should allow different models to be called from PERDI and any other LLM challenges interested in using those models.
- This optimized the first step of the conversation reducing loading times by around 4x.
=> Rafael: Multigenerator and Replicate

backend/app/domain/services/base/context.py, backend/app/domain/services/base/model.py, backend/app/domain/services/utils/llm.py, backend/app/domain/services/utils/multi_generator.py
This PR implements HF API Handler for the factory of LLM Providers, and implemented an asyncio wrapper to handle asynchronous requests even when providers have sync implementations.
-  This should allow different models to be called from PERDI and any other LLM challenges interested in using those models.
- This would allow any provider without an asynchronous implementation to be called by the LLM multigenerator.
=> Implement HF API

api/common/config.py, backend/app/api/endpoints/base/task_proposals.py, backend/app/domain/schemas/base/task_proposals.py, backend/app/domain/services/base/task_proposals.py, backend/app/infrastructure/repositories/task.py, frontends/web/src/common/ApiService.js, frontends/web/src/new_front/components/Modals/CreateProposalTask.tsx, frontends/web/src/new_front/utils/helpers/functions/LoginFunctions.js
We are updating the task proposal creation process. Previously, we required users to provide a task code for their proposals. However, we understand that, in most cases, users may not be aware of the current task codes. As a result, we have decided to remove the task code as a mandatory parameter when creating a proposal. If your proposal is accepted, we will assign an appropriate task code at that time. This change aims to simplify the proposal submission process and make it more user-friendly.
=> feat: Fix remove task code from task proposal

backend/app/domain/services/utils/llm.py
This PR implements conversational templates for Pythia and Falcon.
- This allows models to be correctly called, as the instruction tuning format differed from default Llama2.
=> Include conversational templates for Pythia and Falcon

backend/app/domain/services/utils/llm.py
This PR includes templates for Guanaco and Zephyr instruction tuned models, as well as some additional parameters for the cohere provider.
-  We can now use the instruction tuning template with which Guanaco and Zephyr model families were fine tuned. This should allow better performance, and a fairer evaluation
- We can now define top_k, top_p and max_tokens for each model.
=> Included Zephyr and Guanaco templates

backend/app/domain/services/utils/llm.py
Added an optional flag to the model parameters dictionary which queries the web-search RAG API for Cohere Command
=> Enabled RAG for CohereProvider

backend/app/domain/services/utils/image_generators.py, backend/app/domain/services/utils/llm.py, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/ChatWithInstructions.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/DescribeImage.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectBetweenImagesGenerative.tsx, frontends/web/src/new_front/context/CreateInterface/Context.tsx
This PR implements Several Fixes to the code on the Backend and the FrontEnd listed below:
1. Wonders view (Stop page break when the country and the Language selected were changed if category was selected)
- Clean up localStorageItem after the country was selected.
2. Adversarial-nibbler view (Stop eternal popup when a prompt that has already been submitted is so once more)
- Use variable to know when the popup has appeared and stop firing it again.
3. Prism view (Backend throwing error when trying to create)
- use self.provider_name when provider isn't provided
=> Fix - Bugs on Frontend and Backend

frontends/web/src/new_front/components/Buttons/CreateInterfaceHelpersButton.tsx, frontends/web/src/new_front/components/Buttons/light-mode-override.css
Prevent system darkMode on modal
Overwrite the modal styles using CSS file
=> Fix Modal on DarkMode

frontends/web/src/containers/TaskOwnerPage.js, frontends/web/src/new_front/pages/Task/TaskOwnerPage/ExamplesCreated.tsx
Prevent buttons from getting in front of sidebar
Use Tailwinds responsive features
=> Fix - Buttons on task owner interface

backend/requirements.txt
- In order to work with the same version as the challenge owner we need to update the version of the dependency.
1. Change version Dependecy from 4.27.0 to 5.5.8
=> Update - Cohere Dependency

backend/app/api/endpoints/base/context.py, backend/app/domain/services/base/context.py, backend/app/infrastructure/repositories/context.py
- We need to bring a random context from the context table based in a key and its value inside the context_json column (this column is type text)
1. Add new endpoint to get context random based on the filtered value and its key.
- This should allow the user to see the context filtered.
=> Feature - Get Random Context Endpoint

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectBetweenImagesGenerative.tsx
- The current prompt that we are using in Adversarial-Nibbler is not correct, we are using the new one as a quick-fix but we must implement two stages in a next fixture.
1. Change prompt title and text as required by Nibbler's team.
- This should be more clear to the user.
=> Fix - Nibbler-Prompt

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/AnnotationContextStrategy.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx, frontends/web/src/new_front/components/Inputs/DropdownSearch.tsx, frontends/web/src/new_front/pages/CreateSamples/CreateInterface.tsx, frontends/web/src/new_front/types/createSamples/createSamples/annotationContext.ts, frontends/web/src/new_front/types/createSamples/createSamples/annotationFactory.ts, frontends/web/src/new_front/types/createSamples/createSamples/configurationTask.ts, frontends/web/src/new_front/utils/creation_interface_options.json, frontends/web/src/new_front/utils/helpers/functions/GenerateRandomLightColor.tsx
- For Common Crawl Challenge we needed a component to select in a text several tags and to get a context based on a selection
1. Create Component to select several parts of a text with several tags
- This should allow the user to highlight sections from the text and tag them according with the tag selected.
2. Create Component to search in the different options in a dropdown.
- This should allow the user to search between the different options and shorten the time of interaction with the component.
3. Passed userID to the annotation context strategy component. 
- This would allow the interaction with some endpoints from within the context component.
4. Create Function to generate random light colors.
- This should allow the user to highlight have different colors that would have a good …
=> Feature - Select Text Multiple Tags Component

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectBetweenImagesGenerative.tsx
- Adjust how the comparison of text is done in order for pop up to show
1. use native fetch instead of useFetch
- This would allow to make the call always even if there isn't a change in the parameters.
2. remove add in some function.
- item is a text so we can not get the attribute data from it without it the comparison can me made.
=> remove .data in some item is a text and doesn't have data

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
=> Fast-fix - Remove Slash

backend/app/domain/services/base/context.py, backend/app/infrastructure/models/models.py, backend/app/infrastructure/repositories/context.py, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx
- Text Language Identification Challenge is taking to long to load content, and when Backend throws error the user experience infinite loading
1. Include Alert when backend throws error in specific language.
- This would allow the user to see there is something wrong in the backend and to retrieve english content.
2. Change Context.context_json type from text to JSON.
- apply change to manage JSON type in model and in queries.
=> Fix - Infinite Loading

backend/app/domain/services/base/model.py, backend/app/domain/services/utils/llm.py, backend/app/domain/services/utils/multi_generator.py
This pull request introduces the `OpenRouterProvider` to the codebase and makes several formatting changes to improve readability. The most important changes include adding the new provider to the appropriate lists and dictionaries, and adjusting the formatting of some string assignments.
* [`backend/app/domain/services/utils/llm.py`](diffhunk://#diff-34b4d95fbff2b16b8b430be1cb9f7ba75f3ee101ea4b51036ac24ac9a41246b4R754-R855): Introduced the `OpenRouterProvider` class with methods for text generation and conversational generation.
* [`backend/app/domain/services/base/model.py`](diffhunk://#diff-27c017acbd747f7bf5bc2f4c2926df468f2521dce6cb6515259146b592efde22L211-R218): Reformatted several string assignments to improve readability by splitting long strings into multiple lines. …
=> Included OpenRouter provider

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/ChatRandomWithInstructions.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/Chatbot.tsx
remove render condition not needed inside component, there is a condition before this component so it wasn't needed there
=> Feature - Store Model Random

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/UserInput/AnnotationUserInputStrategy.tsx, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/UserInput/DropDownSingleSelect.tsx, frontends/web/src/new_front/components/Inputs/Dropdown.tsx, frontends/web/src/new_front/components/Lists/DropnDownWithInstructions.tsx, frontends/web/src/new_front/components/Lists/HorizontalRadioButton.tsx, frontends/web/src/new_front/pages/CreateSamples/CreateInterface.tsx, frontends/web/src/new_front/types/createSamples/createSamples/annotationFactory.ts, frontends/web/src/new_front/types/createSamples/createSamples/configurationTask.ts, frontends/web/src/new_front/utils/creation_interface_options.json
-  Challenge owner ask to "group" questions every x number and to add dropdown user input.
1. Include user_input_group_by variable inside context/metadata in yaml file.
- This would allow us to group by a number all the questions (number is always the same).
2. Create dropdown component for user_input section
- This would allow challenges to have a dropdown component for the user input section
=> Feature - DropDown component and Group by in user input

backend/app/api/endpoints/base/context.py, backend/app/domain/schemas/base/context.py, backend/app/domain/services/base/context.py, backend/app/infrastructure/repositories/context.py, frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/SelectMultipleTextMultipleTags.tsx, frontends/web/src/new_front/types/createSamples/createSamples/annotationContext.ts
- Common's Crawl challenge need the context to be distinctive for users.
1. Include distinctive flag in random context con key value.
- This would prevent the users to see text that has been tagged by them.
2. Redirect to task page when there are no more texts to label with the default tag.
- This would prevent the users to be stuck in an infinite loop
=> Fixture - distinctive context

frontends/web/src/new_front/pages/Login/LoginPage.tsx, frontends/web/src/new_front/pages/SubmitModel/SubmitModel.tsx
- When a user who wasn't logged into the platform, clicked on submit model was redirect to login page and then redirect to the wrong page.
1. Include uploadModel to the src url when redirecting to login and read it there.
- This would allow the redirect from login to properly use the src variable and redirect the user where is suppose to be redirected.
=> Fixture - Redirect submit models

frontends/web/src/new_front/components/Tables/Leaderboard/TaskModelLeaderboardCard.jsx, frontends/web/src/new_front/components/Tables/Leaderboard/TaskModelLeaderboardRow.tsx, frontends/web/src/new_front/components/Tables/Leaderboard/TaskModelLeaderboardTable.tsx, frontends/web/src/new_front/pages/Task/TaskPage.tsx
- There were several unnecessary repetitive calls being made from the client as shown in the image.
1. Implement useCallback, useMemo and Memo in several front end components.
- This would prevent unnecessary re-renders and api calls.
=> Fixture - Remove Unnecessary Calls

frontends/web/src/new_front/components/CreateSamples/CreateSamples/AnnotationInterfaces/Contexts/EvaluateTextsGenerative.tsx
- Evaluate Texts Generative had Radio Button burn to be used by participants, if a different input where needed that wouldn't work.
1. Use Annotation User Input Strategy component.
- This would give the owner the option to use different user input on the first step not only radio button.
Make Evaluate Text Generative component work with all the inputs not just with radio button. (we see in the image it is working with input-with-instructions input type)
=> Fixture - Unburn radioButton component
